# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: Bash@3
  inputs:
    script: 'git clone https://github.com/Mobsya/scratch-vm --depth=1'
    targetType: 'inline'
  displayName: 'Cloning scratch vm'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'build'
    archiveFile: '$(Build.ArtifactStagingDirectory)/scratch-gui.tar.gz'
    includeRootFolder: false
    replaceExistingArchive: true
    archiveType: 'tar'
  displayName: 'compressing build directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'scratch-gui'
    


